baseurl = "https://amintasvrp.github.io/myDocs/"
languageCode = "en-us"
title = "myDocs"
theme = "hugo-material-docs"
metadataformat = "yaml"
canonifyurls = true
# Enable Google Analytics by entering your tracking id
googleAnalytics = ""

[params]
	# General information
	author = "Amintas Victor"
	description = "Uma Documentação em Português: Simples e Direta."
	copyright = "Amintas Victor"

	# Repository
	provider = "GitHub"
	repo_url = "https://github.com/amintasvrp/myDocs"

	version = "1.0.0"
	logo = "images/logo.jpeg"
	favicon = ""

	permalink = "#"

	# Custom assets
	custom_css = []
	custom_js  = []

	# Syntax highlighting theme
	highlight_css  = "https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/styles/googlecode.min.css"

	[params.palette]
    	primary = "blue"
    	accent  = "light-blue"

    [params.font]
    	text = "Ubuntu"
    	code = "Ubuntu Mono"


[social]
	twitter = ""
	github  = "amintasvrp"
	email   = "amintas.pereira@ccc.ufcg.edu.br"

[[menu.main]]
	name   = "C"
	url    = "c/"
	weight = 2

[[menu.main]]
	name   = "Haskell"
	url    = "haskell/"
	weight = 2

[[menu.main]]
	name   = "Hugo"
	url    = "hugo/"
	weight = 2

[[menu.main]]
	name   = "Linux"
	url    = "linux/"
	weight = 2

[[menu.main]]
	name   = "Prolog"
	url    = "prolog/"
	weight = 2

[[menu.main]]
	name   = "SQL"
	url    = "sql/"
	weight = 2

[[menu.main]]
	name   = "C++"
	url    = "cpp/"
	weight = 2

[blackfriday]
	smartypants	= true
	fractions = true
	smartDashes = true
	plainIDAnchors = true
